use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Datei",
    edit: "Bearbeiten",
    format: "Format",
    view: "Ansicht",
    new_document: "Neu",
    open_document: "Öffnen...",
    open_recent_file: "Zuletzt geöffnete Datei öffnen",
    no_recent_files: "Keine zuletzt geöffneten Dateien",
    clear_recent_files: "Zuletzt geöffnete Dateien löschen",
    open_folder: "Ordner öffnen...",
    quick_open: "Schnell öffnen...",
    close_document: "Datei schließen",
    save_document: "Speichern",
    save_document_as: "Speichern unter...",
    export: "Exportieren",
    export_pdf: "PDF exportieren",
    export_html: "HTML exportieren",
    export_docx: "DOCX exportieren",
    export_epub: "EPUB exportieren",
    export_latex: "LaTeX exportieren",
    settings: "Einstellungen...",
    check_updates: "Nach Updates suchen",
    undo: "Rückgängig",
    redo: "Wiederholen",
    cut: "Ausschneiden",
    copy: "Kopieren",
    paste: "Einfügen",
    select_all: "Alles auswählen",
    hide: "Markra ausblenden",
    hide_others: "Andere ausblenden",
    show_all: "Alle einblenden",
    quit: "Markra beenden",
    fullscreen: "Vollbildmodus",
    toggle_file_list: "Dateiliste umschalten",
    toggle_markra_ai: "Markra AI umschalten",
    ai_writing_command: "KI-Schreibbefehl",
    toggle_all_folds: "Alles ein-/ausklappen",
    toggle_read_only_mode: "Schreibschutz umschalten",
    toggle_source_mode: "Quellmodus umschalten",
    bold: "Fett",
    italic: "Kursiv",
    strikethrough: "Durchgestrichen",
    inline_code: "Inline-Code",
    paragraph: "Absatz",
    heading_1: "Überschrift 1",
    heading_2: "Überschrift 2",
    heading_3: "Überschrift 3",
    bullet_list: "Aufzählung",
    ordered_list: "Nummerierte Liste",
    quote: "Zitat",
    code_block: "Codeblock",
    link: "Link",
    image: "Bild",
    import_local_images: "Lokale Bilder importieren...",
    table: "Tabelle",
};
